object Versions {
    const val gradle = "7.4.2"
    const val kotlin = "1.6.21"
    const val coreKtx = "1.7.0"
    const val recyclerView = "1.2.1"
    const val nav = "2.5.0"
    const val paging = "3.1.1"
    const val room = "2.4.2"
    const val material = "1.6.0"
    const val constraintLayout = "2.1.3"
    const val appcompat = "1.4.1"
    const val fragment = "1.4.1"
    const val lifecycle = "2.5.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.10.0"
    const val moshi = "1.13.0"
    const val hiltJetpack = "1.0.0"
    const val junit = "4.13.2"
    const val espresso = "3.4.0"
    const val androidxJunit = "1.1.3"
    const val leakCanary = "2.9.1"
    const val glide = "4.13.2"
    const val hilt = "2.42"
    const val mapsplaform_secrets = "2.0.1"
    const val sqlite = "2.3.0"
    const val zeteticSqlCipher = "4.5.3"
}
