name: "CI CD Android"
on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

  workflow_dispatch:

jobs:
  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup secrets.properties
        env:
          API_TOKEN: ${{secrets.API_TOKEN}}
          BASE_URL: ${{secrets.BASE_URL}}
          HOST_NAME: ${{secrets.HOST_NAME}}
          BASE_IMAGE_PATH: ${{secrets.BASE_IMAGE_PATH}}
          DB_PASSPRHASE: ${{secrets.DB_PASSPRHASE}}
          CERTIFICATE_0: ${{secrets.CERTIFICATE_0}}
          CERTIFICATE_1: ${{secrets.CERTIFICATE_1}}
          CERTIFICATE_2: ${{secrets.CERTIFICATE_2}}
        run:
          echo API_TOKEN="$API_TOKEN" > ./secrets.properties
          echo BASE_URL="$BASE_URL" > ./secrets.properties
          echo HOST_NAME="$HOST_NAME" > ./secrets.properties
          echo BASE_IMAGE_PATH="$BASE_IMAGE_PATH" > ./secrets.properties
          echo DB_PASSPRHASE="$DB_PASSPRHASE" > ./secrets.properties
          echo CERTIFICATE_0="$CERTIFICATE_0" > ./secrets.properties
          echo CERTIFICATE_1="$CERTIFICATE_1" > ./secrets.properties
          echo CERTIFICATE_2="$CERTIFICATE_2" > ./secrets.properties

      - name: setup local.properties
        run:
          touch local.properties

      - name: Run Test
        run: |
          ./gradlew test --stacktrace

  android_test:
    name: Run Instrumentation Test
    runs-on: macos-latest
    env:
      API_TOKEN: ${{secrets.API_TOKEN}}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup secrets.properties
        env:
          API_TOKEN: ${{secrets.API_TOKEN}}
          BASE_URL: ${{secrets.BASE_URL}}
          HOST_NAME: ${{secrets.HOST_NAME}}
          BASE_IMAGE_PATH: ${{secrets.BASE_IMAGE_PATH}}
          DB_PASSPRHASE: ${{secrets.DB_PASSPRHASE}}
          CERTIFICATE_0: ${{secrets.CERTIFICATE_0}}
          CERTIFICATE_1: ${{secrets.CERTIFICATE_1}}
          CERTIFICATE_2: ${{secrets.CERTIFICATE_2}}
        run:
          echo API_TOKEN="$API_TOKEN" > ./secrets.properties
          echo BASE_URL="$BASE_URL" > ./secrets.properties
          echo HOST_NAME="$HOST_NAME" > ./secrets.properties
          echo BASE_IMAGE_PATH="$BASE_IMAGE_PATH" > ./secrets.properties
          echo DB_PASSPRHASE="$DB_PASSPRHASE" > ./secrets.properties
          echo CERTIFICATE_0="$CERTIFICATE_0" > ./secrets.properties
          echo CERTIFICATE_1="$CERTIFICATE_1" > ./secrets.properties
          echo CERTIFICATE_2="$CERTIFICATE_2" > ./secrets.properties

      - name: setup local.properties
        run:
          touch local.properties

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  build:
    runs-on: ubuntu-latest
    needs: [ unit_test, android_test ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup secrets.properties
        env:
          API_TOKEN: ${{secrets.API_TOKEN}}
          BASE_URL: ${{secrets.BASE_URL}}
          HOST_NAME: ${{secrets.HOST_NAME}}
          BASE_IMAGE_PATH: ${{secrets.BASE_IMAGE_PATH}}
          DB_PASSPRHASE: ${{secrets.DB_PASSPRHASE}}
          CERTIFICATE_0: ${{secrets.CERTIFICATE_0}}
          CERTIFICATE_1: ${{secrets.CERTIFICATE_1}}
          CERTIFICATE_2: ${{secrets.CERTIFICATE_2}}
        run:
          echo API_TOKEN="$API_TOKEN" > ./secrets.properties
          echo BASE_URL="$BASE_URL" > ./secrets.properties
          echo HOST_NAME="$HOST_NAME" > ./secrets.properties
          echo BASE_IMAGE_PATH="$BASE_IMAGE_PATH" > ./secrets.properties
          echo DB_PASSPRHASE="$DB_PASSPRHASE" > ./secrets.properties
          echo CERTIFICATE_0="$CERTIFICATE_0" > ./secrets.properties
          echo CERTIFICATE_1="$CERTIFICATE_1" > ./secrets.properties
          echo CERTIFICATE_2="$CERTIFICATE_2" > ./secrets.properties

      - name: setup local.properties
        run:
          touch local.properties

      - name: Build APK
        run: ./gradlew build

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Release app
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/debug/app-debug.apk
